FROM node:20-alpine

WORKDIR /app

# Удаляем package-lock.json если он есть, чтобы избежать конфликтов
RUN rm -f package-lock.json

# Копируем файлы зависимостей
COPY ./frontend/package.json ./frontend/yarn.lock ./

# Устанавливаем зависимости через yarn
RUN yarn install --frozen-lockfile

# Копируем остальные файлы frontend
COPY ./frontend/ .

EXPOSE 5173

# ОБЯЗАТЕЛЬНО добавляем --host 0.0.0.0 для работы в контейнере
CMD ["yarn", "dev", "--host", "0.0.0.0"]