"""add_roadmap_table

Revision ID: 4ae06ac324ed
Revises: deff26f838fa
Create Date: 2026-02-06 22:22:00.941950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ae06ac324ed'
down_revision: Union[str, Sequence[str], None] = 'deff26f838fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Название дорожной карты'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='Уникальный слаг дорожной карты'),
    sa.Column('profession', sa.String(length=100), nullable=False, comment='Профессия/специальность (например: Python Developer)'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='Описание дорожной карты'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли дорожная карта'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.create_index('idx_roadmaps_profession_active', ['profession', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmaps_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmaps_profession'), ['profession'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmaps_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_roadmaps_title'), ['title'], unique=False)

    op.create_table('roadmap_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.UUID(), nullable=False, comment='ID дорожной карты'),
    sa.Column('category_id', sa.UUID(), nullable=False, comment='ID категории'),
    sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Список ID вопросов из этой категории (если пусто - все вопросы)'),
    sa.Column('order', sa.Integer(), nullable=False, comment='Порядок элемента в дорожной карте'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmap_items', schema=None) as batch_op:
        batch_op.create_index('idx_roadmap_items_roadmap_order', ['roadmap_id', 'order'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmap_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmap_items_roadmap_id'), ['roadmap_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_items_roadmap_id'))
        batch_op.drop_index(batch_op.f('ix_roadmap_items_category_id'))
        batch_op.drop_index('idx_roadmap_items_roadmap_order')

    op.drop_table('roadmap_items')
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmaps_title'))
        batch_op.drop_index(batch_op.f('ix_roadmaps_slug'))
        batch_op.drop_index(batch_op.f('ix_roadmaps_profession'))
        batch_op.drop_index(batch_op.f('ix_roadmaps_is_active'))
        batch_op.drop_index('idx_roadmaps_profession_active')

    op.drop_table('roadmaps')
    # ### end Alembic commands ###
