"""add_company_tables

Revision ID: bc746442a065
Revises: eb7522cc711c
Create Date: 2026-01-30 16:42:13.158293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc746442a065'
down_revision: Union[str, Sequence[str], None] = 'eb7522cc711c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Название компании'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='Уникальный слаг компании'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='Описание компании'),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='URL логотипа компании'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли компания'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index('idx_companies_slug_active', ['slug', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_slug'), ['slug'], unique=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index('idx_questions_company', ['company_id', 'is_published', 'created_at'], unique=False)
        batch_op.create_index('idx_questions_company_category', ['company_id', 'category_id', 'is_published', 'difficulty'], unique=False)
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_questions_company_category')
        batch_op.drop_index('idx_questions_company')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_slug'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.drop_index(batch_op.f('ix_companies_is_active'))
        batch_op.drop_index('idx_companies_slug_active')

    op.drop_table('companies')
    # ### end Alembic commands ###
