"""add level for company

Revision ID: 521b54d43083
Revises: 4ae06ac324ed
Create Date: 2026-03-15 00:53:47.740534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521b54d43083'
down_revision: Union[str, Sequence[str], None] = '4ae06ac324ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Enum('JUNIOR', 'MIDDLE', 'SENIOR', name='levelcompanyinterview'), nullable=True, comment='Уровень сложности интервью в компании'))
        batch_op.create_index(batch_op.f('ix_companies_level'), ['level'], unique=False)

    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.alter_column('profession',
               existing_type=sa.VARCHAR(length=100),
               comment='Профессия/специальность (например: Backend Developer)',
               existing_comment='Профессия/специальность (например: Python Developer)',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.alter_column('profession',
               existing_type=sa.VARCHAR(length=100),
               comment='Профессия/специальность (например: Python Developer)',
               existing_comment='Профессия/специальность (например: Backend Developer)',
               existing_nullable=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_level'))
        batch_op.drop_column('level')

    # ### end Alembic commands ###
