"""001_Initial migration

Revision ID: 21fc5fc8c38e
Revises: 
Create Date: 2026-01-18 17:34:34.988398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21fc5fc8c38e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название категории'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='Описание категории'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='Уникальный слаг категории'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли категория'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Заголовок вопроса'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='Уникальный слаг вопроса'),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Блоки контента в структурированном формате'),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultyquestionlevel'), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False, comment='ID категории вопроса'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_category', 'questions', ['category_id', 'is_published', 'created_at'], unique=False)
    op.create_index('idx_questions_content_gin', 'questions', ['content'], unique=False, postgresql_using='gin')
    op.create_index('idx_questions_difficulty_published', 'questions', ['difficulty', 'is_published', 'created_at'], unique=False)
    op.create_index(op.f('ix_questions_category_id'), 'questions', ['category_id'], unique=False)
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_is_published'), 'questions', ['is_published'], unique=False)
    op.create_index(op.f('ix_questions_slug'), 'questions', ['slug'], unique=True)
    op.create_index(op.f('ix_questions_title'), 'questions', ['title'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Блоки контента в структурированном формате'),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_is_published'), 'answers', ['is_published'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_table('question_completions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('question_id', sa.UUID(), nullable=False, comment='ID вопроса'),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время отметки выполнения'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question_completion')
    )
    op.create_index('idx_completions_active_users', 'question_completions', ['user_id', 'question_id'], unique=False, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_index('idx_completions_question_count', 'question_completions', ['question_id', 'completed_at'], unique=False)
    op.create_index('idx_completions_user_completed_at', 'question_completions', ['user_id', 'completed_at'], unique=False)
    op.create_index(op.f('ix_question_completions_completed_at'), 'question_completions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_question_completions_question_id'), 'question_completions', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_completions_user_id'), 'question_completions', ['user_id'], unique=False)
    op.create_table('question_favorites',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('question_id', sa.UUID(), nullable=False, comment='ID вопроса'),
    sa.Column('added_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время добавления в избранное'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question_favorite')
    )
    op.create_index('idx_favorites_question_count', 'question_favorites', ['question_id', 'added_at'], unique=False)
    op.create_index('idx_favorites_user_added_at', 'question_favorites', ['user_id', 'added_at'], unique=False)
    op.create_index('idx_favorites_user_question', 'question_favorites', ['user_id', 'question_id'], unique=True)
    op.create_index(op.f('ix_question_favorites_added_at'), 'question_favorites', ['added_at'], unique=False)
    op.create_index(op.f('ix_question_favorites_question_id'), 'question_favorites', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_favorites_user_id'), 'question_favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_favorites_user_id'), table_name='question_favorites')
    op.drop_index(op.f('ix_question_favorites_question_id'), table_name='question_favorites')
    op.drop_index(op.f('ix_question_favorites_added_at'), table_name='question_favorites')
    op.drop_index('idx_favorites_user_question', table_name='question_favorites')
    op.drop_index('idx_favorites_user_added_at', table_name='question_favorites')
    op.drop_index('idx_favorites_question_count', table_name='question_favorites')
    op.drop_table('question_favorites')
    op.drop_index(op.f('ix_question_completions_user_id'), table_name='question_completions')
    op.drop_index(op.f('ix_question_completions_question_id'), table_name='question_completions')
    op.drop_index(op.f('ix_question_completions_completed_at'), table_name='question_completions')
    op.drop_index('idx_completions_user_completed_at', table_name='question_completions')
    op.drop_index('idx_completions_question_count', table_name='question_completions')
    op.drop_index('idx_completions_active_users', table_name='question_completions', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_table('question_completions')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_is_published'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_title'), table_name='questions')
    op.drop_index(op.f('ix_questions_slug'), table_name='questions')
    op.drop_index(op.f('ix_questions_is_published'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_index(op.f('ix_questions_category_id'), table_name='questions')
    op.drop_index('idx_questions_difficulty_published', table_name='questions')
    op.drop_index('idx_questions_content_gin', table_name='questions', postgresql_using='gin')
    op.drop_index('idx_questions_category', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
